mail/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from mail import views


router = routers.DefaultRouter()
router.register(r'mails', views.MailViewSet)
router.register(r'mailrecipients', views.MailRecipientViewSet)
router.register(r'senders', views.SenderTop, base_name='senders')
router.register(r'recipients', views.RecipientTop, base_name='recipients')
router.register(r'graph', views.RawGraph, base_name='graph')

app_name = 'mail'
urlpatterns = [
    url(
        r'^$',
        views.HomeView.as_view(),
        name='home'
    ),
    url(
        r'^graph/',
        views.GraphView.as_view(),
        name='graph'
    ),
    url(
        r'^api/',
        include(router.urls),
    ),
    url(
        r'^mailru/',
        views.mail_ru,
        name='mailru'
    ),
    url(
        r'^gmailcom/',
        views.gmail_com,
        name='gmail'
    ),
    url(
        r'^total/',
        views.total_count,
        name='total'
    )
]

mailstat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from controlcenter.views import controlcenter

urlpatterns = [
    url(r'^', include('mail.urls', namespace='mail')),
    url(r'^admin/', admin.site.urls),
]

reputation/models.py
from django.db import models

# Create your models here.


class Domain(models.Model):
    class Meta:
        verbose_name = 'Домен'
        verbose_name_plural = 'Домены'

    name = models.CharField(unique=True, db_index=True, max_length=255)
    last_check = models.DateTimeField()
    last_total_count = models.PositiveIntegerField()
    last_bounced_count = models.PositiveIntegerField()
    last_deferred_count = models.PositiveIntegerField()
    bounce_rate = models.PositiveIntegerField(db_index=True)
    deferred_rate = models.PositiveIntegerField(db_index=True)
    blocked = models.BooleanField(default=False)
    extended_rate = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Notice(models.Model):
    class Meta:
        verbose_name = 'Примечание'
        verbose_name_plural = 'Примечания'

    domain = models.ForeignKey(Domain, related_name='notices')
    notice = models.TextField()

    def __str__(self):
        return self.notice

reputation/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    <title>Maillog Web Interface</title>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'lodash.min.js' %}"></script>
    <script src="{% static 'semantic/semantic.min.js' %}"></script>
    <script src="https://unpkg.com/vue"></script>
    <script src="https://cdn.jsdelivr.net/vue.resource/1.2.1/vue-resource.min.js"></script>
    <script src="https://momentjs.com/downloads/moment.js"></script>
    <script src="https://momentjs.com/downloads/moment-timezone-with-data.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="https://unpkg.com/flatpickr"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'semantic/semantic.min.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/flatpickr/dist/flatpickr.min.css">

    <style>
        .last.container {
            margin-bottom: 300px !important;
        }
        h1.ui.center.header {
            margin-top: 1em;
        }
        h2.ui.center.header {
            margin: 4em 0em 2em;
        }
        h3.ui.center.header {
            margin-top: 2em;
            padding: 2em 0em;
        }
        div.ui.container {
            margin-top: 2em;
            padding: 2em 0em;
        }
    </style>
</head>
<body>

<h1 class="ui center aligned header">Maillog Web Interface</h1>

<div class="ui three item menu">
    <a class="item" href="{% url 'mail:home' %}">Home</a>
    <a class="item" href="{% url 'mail:graph' %}">Graphs</a>
    <a class="item" href="{% url 'mail:api-root' %}">API</a>
</div>

{% block content %}
{% endblock %}

{% block customscripts %}
{% endblock %}

</body>
</html>